<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[Hi I am Mymethod4]]>
    </line>
    <line>
      <![CDATA[Test case passed]]>
    </line>
    <line>
      <![CDATA[Successful TC name is myMethod4]]>
    </line>
    <line>
      <![CDATA[Screenshot Taken, Please check TC]]>
    </line>
    <line>
      <![CDATA[Failed TC name is myMethod5]]>
    </line>
    <line>
      <![CDATA[TC is skipped, Please check Dependancy]]>
    </line>
    <line>
      <![CDATA[Skipped TC name is myMethod6]]>
    </line>
    <line>
      <![CDATA[Hi I am Mymethod1]]>
    </line>
    <line>
      <![CDATA[Test case passed]]>
    </line>
    <line>
      <![CDATA[Successful TC name is myMethod1]]>
    </line>
    <line>
      <![CDATA[Screenshot Taken, Please check TC]]>
    </line>
    <line>
      <![CDATA[Failed TC name is myMethod2]]>
    </line>
    <line>
      <![CDATA[TC is skipped, Please check Dependancy]]>
    </line>
    <line>
      <![CDATA[Skipped TC name is myMethod3]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-06T23:18:18 IST" name="Suite" finished-at="2022-07-06T23:18:18 IST" duration-ms="99">
    <groups>
    </groups>
    <test started-at="2022-07-06T23:18:18 IST" name="Test" finished-at="2022-07-06T23:18:18 IST" duration-ms="99">
      <class name="ListenerTest.MyTest2">
        <test-method signature="myMethod4()[pri:0, instance:ListenerTest.MyTest2@6e0f5f7f]" started-at="2022-07-06T23:18:18 IST" name="myMethod4" finished-at="2022-07-06T23:18:18 IST" duration-ms="11" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Hi I am Mymethod4]]>
            </line>
            <line>
              <![CDATA[Test case passed]]>
            </line>
            <line>
              <![CDATA[Successful TC name is myMethod4]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod4 -->
        <test-method signature="myMethod5()[pri:0, instance:ListenerTest.MyTest2@6e0f5f7f]" started-at="2022-07-06T23:18:18 IST" name="myMethod5" finished-at="2022-07-06T23:18:18 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at ListenerTest.MyTest2.myMethod5(MyTest2.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Screenshot Taken, Please check TC]]>
            </line>
            <line>
              <![CDATA[Failed TC name is myMethod5]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod5 -->
        <test-method signature="myMethod6()[pri:0, instance:ListenerTest.MyTest2@6e0f5f7f]" started-at="2022-07-06T23:18:18 IST" name="myMethod6" finished-at="2022-07-06T23:18:18 IST" depends-on-methods="ListenerTest.MyTest2.myMethod5" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MyTest2.myMethod6()[pri:0, instance:ListenerTest.MyTest2@6e0f5f7f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MyTest2.myMethod6()[pri:0, instance:ListenerTest.MyTest2@6e0f5f7f] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC is skipped, Please check Dependancy]]>
            </line>
            <line>
              <![CDATA[Skipped TC name is myMethod6]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod6 -->
      </class> <!-- ListenerTest.MyTest2 -->
      <class name="ListenerTest.MyTest">
        <test-method signature="myMethod1()[pri:0, instance:ListenerTest.MyTest@659499f1]" started-at="2022-07-06T23:18:18 IST" name="myMethod1" finished-at="2022-07-06T23:18:18 IST" duration-ms="3" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Hi I am Mymethod1]]>
            </line>
            <line>
              <![CDATA[Test case passed]]>
            </line>
            <line>
              <![CDATA[Successful TC name is myMethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod1 -->
        <test-method signature="myMethod2()[pri:0, instance:ListenerTest.MyTest@659499f1]" started-at="2022-07-06T23:18:18 IST" name="myMethod2" finished-at="2022-07-06T23:18:18 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at ListenerTest.MyTest.myMethod2(MyTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Screenshot Taken, Please check TC]]>
            </line>
            <line>
              <![CDATA[Failed TC name is myMethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod2 -->
        <test-method signature="myMethod3()[pri:0, instance:ListenerTest.MyTest@659499f1]" started-at="2022-07-06T23:18:18 IST" name="myMethod3" finished-at="2022-07-06T23:18:18 IST" depends-on-methods="ListenerTest.MyTest.myMethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MyTest.myMethod3()[pri:0, instance:ListenerTest.MyTest@659499f1] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MyTest.myMethod3()[pri:0, instance:ListenerTest.MyTest@659499f1] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC is skipped, Please check Dependancy]]>
            </line>
            <line>
              <![CDATA[Skipped TC name is myMethod3]]>
            </line>
          </reporter-output>
        </test-method> <!-- myMethod3 -->
      </class> <!-- ListenerTest.MyTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
